language: csharp
mono:
  - beta
branches:
  only:
    - master
sudo: false
#install: curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh
#  | sh && source ~/.dnx/dnvm/dnvm.sh && dnvm upgrade
script:
  dotnet restore && dotnet build ./src/Aqua/ --framework 'netstandard1.6' && dnu build test/Aqua.Tests --framework 'netcoreapp1.0' && dotnet test ./test/Aqua.Tests/