init:
  - git config --global core.autocrlf true
version: 1.0.{build}
before_build:
  - cmd: dotnet restore
build_script:
  - cmd: >-  
      dotnet build src\Aqua
      dotnet build src\Aqua.Newtonsoft.Json
      dotnet build test\Aqua.Tests.TestObjects1
      dotnet build test\Aqua.Tests.TestObjects2
      dotnet build test\Aqua.Tests
test_script:
  - cmd: dotnet test test\Aqua.Tests\Aqua.Tests.csproj
build:
  verbosity: normal