image: Visual Studio 2019

branches:
  except:
  - experimental

init:
  - git config --global core.autocrlf true

version: 1.0.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

before_build:
  - dotnet --info
  - dotnet restore

build_script:
  - dotnet build src\Aqua -c Release
  - dotnet build src\Aqua.Newtonsoft.Json -c Release

test_script:
  - dotnet test test\Aqua.Tests
  - dotnet test test\Aqua.Tests.VBNet

after_test:
  - dotnet clean
  - REM dotnet add test\Aqua.Tests package coverlet.msbuild
  - REM dotnet test test\Aqua.Tests -f net48 /p:CollectCoverage=true /p:CoverletOutputFormat=OpenCover /p:SignAssembly=false
  - dotnet build .\test\Aqua.Tests -f net48 /p:SignAssembly=false
  - dotnet tool install --global coverlet.console
  - coverlet .\test\Aqua.Tests\bin\Debug\net48\Aqua.Tests.dll --target "dotnet" --targetargs "test .\test\Aqua.Tests\ -f net48 --no-build"
  - dotnet tool install --global codecov.tool
  - REM codecov -f test\Aqua.Tests\coverage.opencover.xml
  - codecov -f coverage.opencover.xml

build:
  verbosity: normal